### PR TITLE
Test and Fixes for #6 - Dates in querystring become empty strings

### PR DESCRIPTION
**Pull request by toadzky**
Added test case for ISO date in query string to prove it fails
Overwrite koa request's property `query` to handle dates correctly.

### CODE REVIEW

**Comment by toadzky** [comment]
Closing and re-opening to trigger another build since iojs failed to install

**Comment by martinmicunda** [comment]
@aheckmann is it possible to merge this pull request ?... I am waiting for this fix. Thanks

**Comment by aheckmann** [comment]
i'll pull this down and test + merge once #8 lands (very soon)

On Thu, Dec 3, 2015 at 10:14 AM, Martin Micunda <notifications@github.com>
wrote:

> @aheckmann <https://github.com/aheckmann> is it possible to merge this
> pull request ?... I am waiting for this fix. Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pebble/koa-joi-router/pull/9#issuecomment-161736166>.
>



-- 
Aaron Heckmann
Web Development Lead :: Pebble
https://github.com/aheckmann
https://twitter.com/aaronheckmann

**Comment by martinmicunda** [comment]
Thanks ;)

**Comment by toadzky** [comment]
Sorry, I keep adding things as I need them, so I'm going to close this PR and open it again on separate branch that has just this feature.

**Pull request closed without merging**
